pipeline {
    agent any

    tools {
        maven 'Maven-3.6.3'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/msabale001/Jenkins-Basics-To-Production.git'
            }
        }

        stage('Build Application') {
            steps {
                sh 'mvn clean package'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build Successful!'
        }
        failure {
            echo 'Build Failed!'
        }
    }
}
